title: Armando Maynez
description: 'My personal site.' # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://amaynez.github.io" # the base hostname & protocol for your site, e.g. http://example.com
images: "/images/"

# Author settings
author: Armando Maynez # add your name
author-pic: Myself_Neon_grey.jpg
about-author: Engineer, industry executive, research enthusiast. Avid learner with diverse interests in coding, machine learning, artificial intelligence and reinforcement learning. 17+ years of experience working in multinational corporations.

# Contact links
email: armando.maynez@gmail.com # Add your Email address
phone: # Add your Phone number
website: https://the-mvm.github.io # Add your website, do not add http://
linkedin: amaynez # Add your Linkedin handle
github: amaynez # Add your Github handle
twitter: '@armandomaynez' # Add your Twitter handle
bandcamp: armandomaynez # Add your Bandcamp username

# Tracker
analytics: G-X36ZGJ6FC6
fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: /page:num/
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
highlight_theme: default
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]